project:
  name: "Machine Learning Project"
  version: "1.0"
  random_seed: 42

data:
  train_path: "Data/dataSet.xlsx"
  test_path: "Data/dataSet.xlsx"
  batch_size: 20

model:
  type: "DecisionTreeRegressor"
  hyperparameters:
    max_features": "sqrt"
    max_depth: 9
    random_state: 42
test:
  data_load: "Tests/test_data_loader.py"
  modle: "Tests/test_model.py"
  preprocess: "Tests/test_preprocess"
